name: 'Hello World'
description: 'Greet someone'
runs:
  using: 'docker'
  image: 'Dockerfile'
env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
